services:
  integration-postgres-tests:
    profiles: ["pgsql"]
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TEST_OUTBOXLIB_PSQL_DATABASENAME:-tests-db-pgsql}
      POSTGRES_USER: ${TEST_OUTBOXLIB_PSQL_USERNAME:-tests-service}
      POSTGRES_PASSWORD: ${TEST_OUTBOXLIB_PSQL_PASSWORD:-tests-service}
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:${TEST_OUTBOXLIB_PSQL_PORT_LOCAL:-54335}:5432"
    expose:
      - "${TEST_OUTBOXLIB_PSQL_PORT:-5432}"

  integration-mysql-tests:
    profiles: ["mysql"]
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_OUTBOXLIB_MYSQL_PASSWORD:-tests-service}
      MYSQL_DATABASE: ${TEST_OUTBOXLIB_MYSQL_DATABASENAME:-tests-db-mysql}
    ports:
      - "127.0.0.1:${TEST_OUTBOXLIB_MYSQL_PORT_LOCAL:-33306}:3306"
    expose:
      - "${TEST_OUTBOXLIB_MYSQL_PORT:-3306}"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --log-bin-trust-function-creators=1

  integration-picodata-tests:
    profiles: ["picodata"]
    image: docker-public.binary.picodata.io/picodata:25.2.2
    hostname: integration-picodata-tests
    environment:
      PICODATA_CLUSTER_NAME: ${TEST_OUTBOXLIB_PICODATA_CLUSTER_NAME:-app_outbox_tests}
      PICODATA_INSTANCE_NAME: integration-picodata-tests
      PICODATA_INSTANCE_DIR: /tmp/pico/data/integration-picodata-tests
      PICODATA_PEER: integration-picodata-tests:${TEST_OUTBOXLIB_PICODATA_LISTEN_PEER:-3349}
      PICODATA_IPROTO_LISTEN: 0.0.0.0:${TEST_OUTBOXLIB_PICODATA_LISTEN_PEER:-3349}
      PICODATA_IPROTO_ADVERTISE: integration-picodata-tests:${TEST_OUTBOXLIB_PICODATA_LISTEN_PEER:-3349}
      PICODATA_FAILURE_DOMAIN: HOST=integration-picodata-tests
      PICODATA_INIT_REPLICATION_FACTOR: ${TEST_OUTBOXLIB_PICODATA_INIT_REPLICATION_FACTOR:-1}
      PICODATA_INIT_BUCKET_COUNT: ${TEST_OUTBOXLIB_PICODATA_INIT_BUCKET_COUNT:-10}
      PICODATA_HTTP_LISTEN: 0.0.0.0:${TEST_OUTBOXLIB_PICODATA_LISTEN_HTTP:-8049}
      PICODATA_PG_LISTEN: 0.0.0.0:${TEST_OUTBOXLIB_PICODATA_LISTEN_PG:-5049}
      PICODATA_MEMTX_MEMORY: ${TEST_OUTBOXLIB_PICODATA_MEMTX_MEMORY:-64M}
      PICODATA_MEMTX_SYSTEM_MEMORY: ${TEST_OUTBOXLIB_PICODATA_MEMTX_SYSTEM_MEMORY:-256M}
      PICODATA_MEMTX_MAX_TUPLE_SIZE: ${TEST_OUTBOXLIB_PICODATA_MEMTX_MAX_TUPLE_SIZE:-1M}
      PICODATA_LOG_LEVEL: info
      PICODATA_PG_SSL: ${TEST_OUTBOXLIB_PICODATA_PG_SSL:-false}
      PICODATA_ADMIN_PASSWORD: ${TEST_OUTBOXLIB_PICODATA_ADMIN_PASSWORD}
    ports:
      - ${TEST_OUTBOXLIB_PICODATA_LISTEN_PEER:-3349}:3349
      - ${TEST_OUTBOXLIB_PICODATA_LISTEN_PG:-5049}:5049
      - ${TEST_OUTBOXLIB_PICODATA_LISTEN_HTTP:-8049}:8049
    volumes:
      - ./docker/picodata/share_dir:/app/share_dir
