services:
  integration-postgres-tests:
    profiles: ["pgsql"]
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${TEST_OUTBOXLIB_PSQL_DATABASENAME:-tests-db-pgsql}
      POSTGRES_USER: ${TEST_OUTBOXLIB_PSQL_USERNAME:-tests-service}
      POSTGRES_PASSWORD: ${TEST_OUTBOXLIB_PSQL_PASSWORD:-tests-service}
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:${TEST_OUTBOXLIB_PSQL_PORT_LOCAL:-54325}:5432"
    expose:
      - "${TEST_OUTBOXLIB_PSQL_PORT:-5432}"

  integration-mysql-tests:
    profiles: ["mysql"]
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_OUTBOXLIB_MYSQL_PASSWORD:-tests-service}
      MYSQL_DATABASE: ${TEST_OUTBOXLIB_MYSQL_DATABASENAME:-tests-db-mysql}
    ports:
      - "127.0.0.1:${TEST_OUTBOXLIB_MYSQL_PORT_LOCAL:-33306}:3306"
    expose:
      - "${TEST_OUTBOXLIB_MYSQL_PORT:-3306}"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --log-bin-trust-function-creators=1

  integration-picodata-tests:
    profiles: ["picodata"]
    build:
      context: ./
      dockerfile: ./docker/picodata/Dockerfile
    hostname: integration-picodata-tests
    environment:
      PICODATA_INSTANCE_NAME: integration-picodata-tests
      PICODATA_INSTANCE_DIR: /tmp/pico/data/integration-picodata-tests
      PICODATA_IPROTO_LISTEN: 0.0.0.0:${PICODATA_LISTEN_PEER_TESTS:-3349}
      PICODATA_IPROTO_ADVERTISE: 0.0.0.0:${PICODATA_LISTEN_PEER_TESTS:-3349}
      PICODATA_PG_LISTEN: 0.0.0.0:${PICODATA_LISTEN_PG_TESTS:-5049}
      PICODATA_PG_SSL: ${TEST_OUTBOXLIB_PICODATA_PG_SSL:-false}
      PICODATA_ADMIN_PASSWORD: ${TEST_OUTBOXLIB_PICODATA_ADMIN_PASSWORD}
      PICODATA_CONFIG_FILE: /app/cluster-storage.yml
    ports:
      - ${PICODATA_LISTEN_PEER_TESTS:-3349}:3349
      - ${PICODATA_LISTEN_PG_TESTS:-5049}:5049
      - ${PICODATA_LISTEN_HTTP_TESTS:-8049}:8049
    volumes:
      - ./docker/picodata/cluster-storage-tests.yml:/app/cluster-storage.yml
      - ./docker/picodata/share_dir:/app/share_dir
