// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mocks/client_mock.gen.go -package=transportmocks
//

// Package transportmocks is a generated GoMock package.
package transportmocks

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	transporthttp "github.com/assurrussa/outbox/infrastructure/transport/http"
)

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPClient) Do(ctx context.Context, method, url string, body io.Reader, headers transporthttp.RequestHeaders) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, method, url, body, headers)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientMockRecorder) Do(ctx, method, url, body, headers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPClient)(nil).Do), ctx, method, url, body, headers)
}

// DoWithRequest mocks base method.
func (m *MockHTTPClient) DoWithRequest(ctx context.Context, request transporthttp.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoWithRequest", ctx, request)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoWithRequest indicates an expected call of DoWithRequest.
func (mr *MockHTTPClientMockRecorder) DoWithRequest(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWithRequest", reflect.TypeOf((*MockHTTPClient)(nil).DoWithRequest), ctx, request)
}

// DoWithRequestAndParse mocks base method.
func (m *MockHTTPClient) DoWithRequestAndParse(ctx context.Context, request transporthttp.Request, data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoWithRequestAndParse", ctx, request, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoWithRequestAndParse indicates an expected call of DoWithRequestAndParse.
func (mr *MockHTTPClientMockRecorder) DoWithRequestAndParse(ctx, request, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoWithRequestAndParse", reflect.TypeOf((*MockHTTPClient)(nil).DoWithRequestAndParse), ctx, request, data)
}
