// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract_mock.gen.go -package=storagemocks
//

// Package storagemocks is a generated GoMock package.
package storagemocks

import (
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	gomock "go.uber.org/mock/gomock"

	storage "github.com/assurrussa/outbox/infrastructure/pgsql/storage"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// DB mocks base method.
func (m *MockClient) DB() storage.DBEngine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(storage.DBEngine)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockClientMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockClient)(nil).DB))
}

// MockSqlizer is a mock of Sqlizer interface.
type MockSqlizer struct {
	ctrl     *gomock.Controller
	recorder *MockSqlizerMockRecorder
	isgomock struct{}
}

// MockSqlizerMockRecorder is the mock recorder for MockSqlizer.
type MockSqlizerMockRecorder struct {
	mock *MockSqlizer
}

// NewMockSqlizer creates a new mock instance.
func NewMockSqlizer(ctrl *gomock.Controller) *MockSqlizer {
	mock := &MockSqlizer{ctrl: ctrl}
	mock.recorder = &MockSqlizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSqlizer) EXPECT() *MockSqlizerMockRecorder {
	return m.recorder
}

// ToSql mocks base method.
func (m *MockSqlizer) ToSql() (string, []any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToSql")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ToSql indicates an expected call of ToSql.
func (mr *MockSqlizerMockRecorder) ToSql() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToSql", reflect.TypeOf((*MockSqlizer)(nil).ToSql))
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockTransactor) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockTransactorMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockTransactor)(nil).BeginTx), ctx, txOptions)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// ReadCommitted mocks base method.
func (m *MockTxManager) ReadCommitted(ctx context.Context, accessMode pgx.TxAccessMode, fn storage.FnCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCommitted", ctx, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadCommitted indicates an expected call of ReadCommitted.
func (mr *MockTxManagerMockRecorder) ReadCommitted(ctx, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCommitted", reflect.TypeOf((*MockTxManager)(nil).ReadCommitted), ctx, accessMode, fn)
}

// RepeatableRead mocks base method.
func (m *MockTxManager) RepeatableRead(ctx context.Context, accessMode pgx.TxAccessMode, fn storage.FnCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepeatableRead", ctx, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RepeatableRead indicates an expected call of RepeatableRead.
func (mr *MockTxManagerMockRecorder) RepeatableRead(ctx, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepeatableRead", reflect.TypeOf((*MockTxManager)(nil).RepeatableRead), ctx, accessMode, fn)
}

// RunInTx mocks base method.
func (m *MockTxManager) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTxManagerMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTxManager)(nil).RunInTx), ctx, f)
}

// Serializable mocks base method.
func (m *MockTxManager) Serializable(ctx context.Context, accessMode pgx.TxAccessMode, fn storage.FnCallback) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Serializable", ctx, accessMode, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Serializable indicates an expected call of Serializable.
func (mr *MockTxManagerMockRecorder) Serializable(ctx, accessMode, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Serializable", reflect.TypeOf((*MockTxManager)(nil).Serializable), ctx, accessMode, fn)
}

// MockPinger is a mock of Pinger interface.
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPingerMockRecorder
	isgomock struct{}
}

// MockPingerMockRecorder is the mock recorder for MockPinger.
type MockPingerMockRecorder struct {
	mock *MockPinger
}

// NewMockPinger creates a new mock instance.
func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &MockPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinger) EXPECT() *MockPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockPinger) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPingerMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPinger)(nil).Ping), ctx)
}

// MockNamedExecer is a mock of NamedExecer interface.
type MockNamedExecer struct {
	ctrl     *gomock.Controller
	recorder *MockNamedExecerMockRecorder
	isgomock struct{}
}

// MockNamedExecerMockRecorder is the mock recorder for MockNamedExecer.
type MockNamedExecerMockRecorder struct {
	mock *MockNamedExecer
}

// NewMockNamedExecer creates a new mock instance.
func NewMockNamedExecer(ctrl *gomock.Controller) *MockNamedExecer {
	mock := &MockNamedExecer{ctrl: ctrl}
	mock.recorder = &MockNamedExecerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamedExecer) EXPECT() *MockNamedExecerMockRecorder {
	return m.recorder
}

// ScanAll mocks base method.
func (m *MockNamedExecer) ScanAll(ctx context.Context, operationName string, dest any, sql string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, dest, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanAll indicates an expected call of ScanAll.
func (mr *MockNamedExecerMockRecorder) ScanAll(ctx, operationName, dest, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, dest, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAll", reflect.TypeOf((*MockNamedExecer)(nil).ScanAll), varargs...)
}

// ScanOne mocks base method.
func (m *MockNamedExecer) ScanOne(ctx context.Context, operationName string, dest any, sql string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, dest, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanOne indicates an expected call of ScanOne.
func (mr *MockNamedExecerMockRecorder) ScanOne(ctx, operationName, dest, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, dest, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanOne", reflect.TypeOf((*MockNamedExecer)(nil).ScanOne), varargs...)
}

// MockNamedExecerSqlizer is a mock of NamedExecerSqlizer interface.
type MockNamedExecerSqlizer struct {
	ctrl     *gomock.Controller
	recorder *MockNamedExecerSqlizerMockRecorder
	isgomock struct{}
}

// MockNamedExecerSqlizerMockRecorder is the mock recorder for MockNamedExecerSqlizer.
type MockNamedExecerSqlizerMockRecorder struct {
	mock *MockNamedExecerSqlizer
}

// NewMockNamedExecerSqlizer creates a new mock instance.
func NewMockNamedExecerSqlizer(ctrl *gomock.Controller) *MockNamedExecerSqlizer {
	mock := &MockNamedExecerSqlizer{ctrl: ctrl}
	mock.recorder = &MockNamedExecerSqlizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamedExecerSqlizer) EXPECT() *MockNamedExecerSqlizerMockRecorder {
	return m.recorder
}

// ScanAllx mocks base method.
func (m *MockNamedExecerSqlizer) ScanAllx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanAllx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanAllx indicates an expected call of ScanAllx.
func (mr *MockNamedExecerSqlizerMockRecorder) ScanAllx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAllx", reflect.TypeOf((*MockNamedExecerSqlizer)(nil).ScanAllx), ctx, operationName, dest, sqlizer)
}

// ScanOnex mocks base method.
func (m *MockNamedExecerSqlizer) ScanOnex(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanOnex", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanOnex indicates an expected call of ScanOnex.
func (mr *MockNamedExecerSqlizerMockRecorder) ScanOnex(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanOnex", reflect.TypeOf((*MockNamedExecerSqlizer)(nil).ScanOnex), ctx, operationName, dest, sqlizer)
}

// MockQueryExecer is a mock of QueryExecer interface.
type MockQueryExecer struct {
	ctrl     *gomock.Controller
	recorder *MockQueryExecerMockRecorder
	isgomock struct{}
}

// MockQueryExecerMockRecorder is the mock recorder for MockQueryExecer.
type MockQueryExecerMockRecorder struct {
	mock *MockQueryExecer
}

// NewMockQueryExecer creates a new mock instance.
func NewMockQueryExecer(ctrl *gomock.Controller) *MockQueryExecer {
	mock := &MockQueryExecer{ctrl: ctrl}
	mock.recorder = &MockQueryExecerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryExecer) EXPECT() *MockQueryExecerMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockQueryExecer) Exec(ctx context.Context, operationName, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockQueryExecerMockRecorder) Exec(ctx, operationName, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockQueryExecer)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockQueryExecer) Query(ctx context.Context, operationName, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockQueryExecerMockRecorder) Query(ctx, operationName, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryExecer)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockQueryExecer) QueryRow(ctx context.Context, operationName, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockQueryExecerMockRecorder) QueryRow(ctx, operationName, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockQueryExecer)(nil).QueryRow), varargs...)
}

// MockQueryExecerSqlizer is a mock of QueryExecerSqlizer interface.
type MockQueryExecerSqlizer struct {
	ctrl     *gomock.Controller
	recorder *MockQueryExecerSqlizerMockRecorder
	isgomock struct{}
}

// MockQueryExecerSqlizerMockRecorder is the mock recorder for MockQueryExecerSqlizer.
type MockQueryExecerSqlizerMockRecorder struct {
	mock *MockQueryExecerSqlizer
}

// NewMockQueryExecerSqlizer creates a new mock instance.
func NewMockQueryExecerSqlizer(ctrl *gomock.Controller) *MockQueryExecerSqlizer {
	mock := &MockQueryExecerSqlizer{ctrl: ctrl}
	mock.recorder = &MockQueryExecerSqlizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryExecerSqlizer) EXPECT() *MockQueryExecerSqlizerMockRecorder {
	return m.recorder
}

// Execx mocks base method.
func (m *MockQueryExecerSqlizer) Execx(ctx context.Context, operationName string, sqlizer storage.Sqlizer) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execx", ctx, operationName, sqlizer)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execx indicates an expected call of Execx.
func (mr *MockQueryExecerSqlizerMockRecorder) Execx(ctx, operationName, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execx", reflect.TypeOf((*MockQueryExecerSqlizer)(nil).Execx), ctx, operationName, sqlizer)
}

// Getx mocks base method.
func (m *MockQueryExecerSqlizer) Getx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Getx indicates an expected call of Getx.
func (mr *MockQueryExecerSqlizerMockRecorder) Getx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getx", reflect.TypeOf((*MockQueryExecerSqlizer)(nil).Getx), ctx, operationName, dest, sqlizer)
}

// Selectx mocks base method.
func (m *MockQueryExecerSqlizer) Selectx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selectx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Selectx indicates an expected call of Selectx.
func (mr *MockQueryExecerSqlizerMockRecorder) Selectx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selectx", reflect.TypeOf((*MockQueryExecerSqlizer)(nil).Selectx), ctx, operationName, dest, sqlizer)
}

// MockBatcherExtended is a mock of BatcherExtended interface.
type MockBatcherExtended struct {
	ctrl     *gomock.Controller
	recorder *MockBatcherExtendedMockRecorder
	isgomock struct{}
}

// MockBatcherExtendedMockRecorder is the mock recorder for MockBatcherExtended.
type MockBatcherExtendedMockRecorder struct {
	mock *MockBatcherExtended
}

// NewMockBatcherExtended creates a new mock instance.
func NewMockBatcherExtended(ctrl *gomock.Controller) *MockBatcherExtended {
	mock := &MockBatcherExtended{ctrl: ctrl}
	mock.recorder = &MockBatcherExtendedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatcherExtended) EXPECT() *MockBatcherExtendedMockRecorder {
	return m.recorder
}

// CopyFrom mocks base method.
func (m *MockBatcherExtended) CopyFrom(ctx context.Context, operationName string, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, operationName, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockBatcherExtendedMockRecorder) CopyFrom(ctx, operationName, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockBatcherExtended)(nil).CopyFrom), ctx, operationName, tableName, columnNames, rowSrc)
}

// SendBatch mocks base method.
func (m *MockBatcherExtended) SendBatch(ctx context.Context, operationName string, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, operationName, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockBatcherExtendedMockRecorder) SendBatch(ctx, operationName, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockBatcherExtended)(nil).SendBatch), ctx, operationName, b)
}

// MockSQLExecer is a mock of SQLExecer interface.
type MockSQLExecer struct {
	ctrl     *gomock.Controller
	recorder *MockSQLExecerMockRecorder
	isgomock struct{}
}

// MockSQLExecerMockRecorder is the mock recorder for MockSQLExecer.
type MockSQLExecerMockRecorder struct {
	mock *MockSQLExecer
}

// NewMockSQLExecer creates a new mock instance.
func NewMockSQLExecer(ctrl *gomock.Controller) *MockSQLExecer {
	mock := &MockSQLExecer{ctrl: ctrl}
	mock.recorder = &MockSQLExecerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLExecer) EXPECT() *MockSQLExecerMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockSQLExecer) Exec(ctx context.Context, operationName, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockSQLExecerMockRecorder) Exec(ctx, operationName, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockSQLExecer)(nil).Exec), varargs...)
}

// Execx mocks base method.
func (m *MockSQLExecer) Execx(ctx context.Context, operationName string, sqlizer storage.Sqlizer) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execx", ctx, operationName, sqlizer)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execx indicates an expected call of Execx.
func (mr *MockSQLExecerMockRecorder) Execx(ctx, operationName, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execx", reflect.TypeOf((*MockSQLExecer)(nil).Execx), ctx, operationName, sqlizer)
}

// Getx mocks base method.
func (m *MockSQLExecer) Getx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Getx indicates an expected call of Getx.
func (mr *MockSQLExecerMockRecorder) Getx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getx", reflect.TypeOf((*MockSQLExecer)(nil).Getx), ctx, operationName, dest, sqlizer)
}

// Query mocks base method.
func (m *MockSQLExecer) Query(ctx context.Context, operationName, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockSQLExecerMockRecorder) Query(ctx, operationName, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockSQLExecer)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockSQLExecer) QueryRow(ctx context.Context, operationName, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockSQLExecerMockRecorder) QueryRow(ctx, operationName, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockSQLExecer)(nil).QueryRow), varargs...)
}

// ScanAll mocks base method.
func (m *MockSQLExecer) ScanAll(ctx context.Context, operationName string, dest any, sql string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, dest, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanAll indicates an expected call of ScanAll.
func (mr *MockSQLExecerMockRecorder) ScanAll(ctx, operationName, dest, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, dest, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAll", reflect.TypeOf((*MockSQLExecer)(nil).ScanAll), varargs...)
}

// ScanAllx mocks base method.
func (m *MockSQLExecer) ScanAllx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanAllx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanAllx indicates an expected call of ScanAllx.
func (mr *MockSQLExecerMockRecorder) ScanAllx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAllx", reflect.TypeOf((*MockSQLExecer)(nil).ScanAllx), ctx, operationName, dest, sqlizer)
}

// ScanOne mocks base method.
func (m *MockSQLExecer) ScanOne(ctx context.Context, operationName string, dest any, sql string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, dest, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanOne indicates an expected call of ScanOne.
func (mr *MockSQLExecerMockRecorder) ScanOne(ctx, operationName, dest, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, dest, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanOne", reflect.TypeOf((*MockSQLExecer)(nil).ScanOne), varargs...)
}

// ScanOnex mocks base method.
func (m *MockSQLExecer) ScanOnex(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanOnex", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanOnex indicates an expected call of ScanOnex.
func (mr *MockSQLExecerMockRecorder) ScanOnex(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanOnex", reflect.TypeOf((*MockSQLExecer)(nil).ScanOnex), ctx, operationName, dest, sqlizer)
}

// Selectx mocks base method.
func (m *MockSQLExecer) Selectx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selectx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Selectx indicates an expected call of Selectx.
func (mr *MockSQLExecerMockRecorder) Selectx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selectx", reflect.TypeOf((*MockSQLExecer)(nil).Selectx), ctx, operationName, dest, sqlizer)
}

// MockDBEngine is a mock of DBEngine interface.
type MockDBEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDBEngineMockRecorder
	isgomock struct{}
}

// MockDBEngineMockRecorder is the mock recorder for MockDBEngine.
type MockDBEngineMockRecorder struct {
	mock *MockDBEngine
}

// NewMockDBEngine creates a new mock instance.
func NewMockDBEngine(ctrl *gomock.Controller) *MockDBEngine {
	mock := &MockDBEngine{ctrl: ctrl}
	mock.recorder = &MockDBEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBEngine) EXPECT() *MockDBEngineMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDBEngine) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDBEngineMockRecorder) BeginTx(ctx, txOptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDBEngine)(nil).BeginTx), ctx, txOptions)
}

// Close mocks base method.
func (m *MockDBEngine) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDBEngineMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDBEngine)(nil).Close))
}

// CopyFrom mocks base method.
func (m *MockDBEngine) CopyFrom(ctx context.Context, operationName string, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFrom", ctx, operationName, tableName, columnNames, rowSrc)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CopyFrom indicates an expected call of CopyFrom.
func (mr *MockDBEngineMockRecorder) CopyFrom(ctx, operationName, tableName, columnNames, rowSrc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFrom", reflect.TypeOf((*MockDBEngine)(nil).CopyFrom), ctx, operationName, tableName, columnNames, rowSrc)
}

// Exec mocks base method.
func (m *MockDBEngine) Exec(ctx context.Context, operationName, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBEngineMockRecorder) Exec(ctx, operationName, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDBEngine)(nil).Exec), varargs...)
}

// Execx mocks base method.
func (m *MockDBEngine) Execx(ctx context.Context, operationName string, sqlizer storage.Sqlizer) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execx", ctx, operationName, sqlizer)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execx indicates an expected call of Execx.
func (mr *MockDBEngineMockRecorder) Execx(ctx, operationName, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execx", reflect.TypeOf((*MockDBEngine)(nil).Execx), ctx, operationName, sqlizer)
}

// Getx mocks base method.
func (m *MockDBEngine) Getx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Getx indicates an expected call of Getx.
func (mr *MockDBEngineMockRecorder) Getx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getx", reflect.TypeOf((*MockDBEngine)(nil).Getx), ctx, operationName, dest, sqlizer)
}

// Ping mocks base method.
func (m *MockDBEngine) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDBEngineMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDBEngine)(nil).Ping), ctx)
}

// Pool mocks base method.
func (m *MockDBEngine) Pool() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pool")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// Pool indicates an expected call of Pool.
func (mr *MockDBEngineMockRecorder) Pool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pool", reflect.TypeOf((*MockDBEngine)(nil).Pool))
}

// Query mocks base method.
func (m *MockDBEngine) Query(ctx context.Context, operationName, sql string, args ...any) (pgx.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(pgx.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBEngineMockRecorder) Query(ctx, operationName, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDBEngine)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockDBEngine) QueryRow(ctx context.Context, operationName, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBEngineMockRecorder) QueryRow(ctx, operationName, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDBEngine)(nil).QueryRow), varargs...)
}

// ScanAll mocks base method.
func (m *MockDBEngine) ScanAll(ctx context.Context, operationName string, dest any, sql string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, dest, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanAll", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanAll indicates an expected call of ScanAll.
func (mr *MockDBEngineMockRecorder) ScanAll(ctx, operationName, dest, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, dest, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAll", reflect.TypeOf((*MockDBEngine)(nil).ScanAll), varargs...)
}

// ScanAllx mocks base method.
func (m *MockDBEngine) ScanAllx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanAllx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanAllx indicates an expected call of ScanAllx.
func (mr *MockDBEngineMockRecorder) ScanAllx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanAllx", reflect.TypeOf((*MockDBEngine)(nil).ScanAllx), ctx, operationName, dest, sqlizer)
}

// ScanOne mocks base method.
func (m *MockDBEngine) ScanOne(ctx context.Context, operationName string, dest any, sql string, args ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, operationName, dest, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanOne", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanOne indicates an expected call of ScanOne.
func (mr *MockDBEngineMockRecorder) ScanOne(ctx, operationName, dest, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, operationName, dest, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanOne", reflect.TypeOf((*MockDBEngine)(nil).ScanOne), varargs...)
}

// ScanOnex mocks base method.
func (m *MockDBEngine) ScanOnex(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanOnex", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanOnex indicates an expected call of ScanOnex.
func (mr *MockDBEngineMockRecorder) ScanOnex(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanOnex", reflect.TypeOf((*MockDBEngine)(nil).ScanOnex), ctx, operationName, dest, sqlizer)
}

// Selectx mocks base method.
func (m *MockDBEngine) Selectx(ctx context.Context, operationName string, dest any, sqlizer storage.Sqlizer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Selectx", ctx, operationName, dest, sqlizer)
	ret0, _ := ret[0].(error)
	return ret0
}

// Selectx indicates an expected call of Selectx.
func (mr *MockDBEngineMockRecorder) Selectx(ctx, operationName, dest, sqlizer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Selectx", reflect.TypeOf((*MockDBEngine)(nil).Selectx), ctx, operationName, dest, sqlizer)
}

// SendBatch mocks base method.
func (m *MockDBEngine) SendBatch(ctx context.Context, operationName string, b *pgx.Batch) pgx.BatchResults {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBatch", ctx, operationName, b)
	ret0, _ := ret[0].(pgx.BatchResults)
	return ret0
}

// SendBatch indicates an expected call of SendBatch.
func (mr *MockDBEngineMockRecorder) SendBatch(ctx, operationName, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBatch", reflect.TypeOf((*MockDBEngine)(nil).SendBatch), ctx, operationName, b)
}

// MockDBPgxEnginePool is a mock of DBPgxEnginePool interface.
type MockDBPgxEnginePool struct {
	ctrl     *gomock.Controller
	recorder *MockDBPgxEnginePoolMockRecorder
	isgomock struct{}
}

// MockDBPgxEnginePoolMockRecorder is the mock recorder for MockDBPgxEnginePool.
type MockDBPgxEnginePoolMockRecorder struct {
	mock *MockDBPgxEnginePool
}

// NewMockDBPgxEnginePool creates a new mock instance.
func NewMockDBPgxEnginePool(ctrl *gomock.Controller) *MockDBPgxEnginePool {
	mock := &MockDBPgxEnginePool{ctrl: ctrl}
	mock.recorder = &MockDBPgxEnginePoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBPgxEnginePool) EXPECT() *MockDBPgxEnginePoolMockRecorder {
	return m.recorder
}

// Pool mocks base method.
func (m *MockDBPgxEnginePool) Pool() *pgxpool.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pool")
	ret0, _ := ret[0].(*pgxpool.Pool)
	return ret0
}

// Pool indicates an expected call of Pool.
func (mr *MockDBPgxEnginePoolMockRecorder) Pool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pool", reflect.TypeOf((*MockDBPgxEnginePool)(nil).Pool))
}
