// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract_mock.gen.go -package=outboxmocks
//

// Package outboxmocks is a generated GoMock package.
package outboxmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	outbox "github.com/assurrussa/outbox/outbox"
	models "github.com/assurrussa/outbox/outbox/models"
	types "github.com/assurrussa/outbox/shared/types"
)

// MockPutter is a mock of Putter interface.
type MockPutter struct {
	ctrl     *gomock.Controller
	recorder *MockPutterMockRecorder
	isgomock struct{}
}

// MockPutterMockRecorder is the mock recorder for MockPutter.
type MockPutterMockRecorder struct {
	mock *MockPutter
}

// NewMockPutter creates a new mock instance.
func NewMockPutter(ctrl *gomock.Controller) *MockPutter {
	mock := &MockPutter{ctrl: ctrl}
	mock.recorder = &MockPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPutter) EXPECT() *MockPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockStats is a mock of Stats interface.
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *MockStatsMockRecorder
	isgomock struct{}
}

// MockStatsMockRecorder is the mock recorder for MockStats.
type MockStatsMockRecorder struct {
	mock *MockStats
}

// NewMockStats creates a new mock instance.
func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &MockStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStats) EXPECT() *MockStatsMockRecorder {
	return m.recorder
}

// QueueStats mocks base method.
func (m *MockStats) QueueStats(ctx context.Context) (outbox.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueStats", ctx)
	ret0, _ := ret[0].(outbox.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueStats indicates an expected call of QueueStats.
func (mr *MockStatsMockRecorder) QueueStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueStats", reflect.TypeOf((*MockStats)(nil).QueueStats), ctx)
}

// MockJobsRepository is a mock of JobsRepository interface.
type MockJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsRepositoryMockRecorder is the mock recorder for MockJobsRepository.
type MockJobsRepositoryMockRecorder struct {
	mock *MockJobsRepository
}

// NewMockJobsRepository creates a new mock instance.
func NewMockJobsRepository(ctrl *gomock.Controller) *MockJobsRepository {
	mock := &MockJobsRepository{ctrl: ctrl}
	mock.recorder = &MockJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsRepository) EXPECT() *MockJobsRepositoryMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobsRepository) CreateJob(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobsRepositoryMockRecorder) CreateJob(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobsRepository)(nil).CreateJob), ctx, name, payload, availableAt)
}

// DeleteJob mocks base method.
func (m *MockJobsRepository) DeleteJob(ctx context.Context, jobID types.JobID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", ctx, jobID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockJobsRepositoryMockRecorder) DeleteJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockJobsRepository)(nil).DeleteJob), ctx, jobID)
}

// FindAndReserveJob mocks base method.
func (m *MockJobsRepository) FindAndReserveJob(ctx context.Context, now, until time.Time) (models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAndReserveJob", ctx, now, until)
	ret0, _ := ret[0].(models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAndReserveJob indicates an expected call of FindAndReserveJob.
func (mr *MockJobsRepositoryMockRecorder) FindAndReserveJob(ctx, now, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAndReserveJob", reflect.TypeOf((*MockJobsRepository)(nil).FindAndReserveJob), ctx, now, until)
}

// MockJobsStatRepository is a mock of JobsStatRepository interface.
type MockJobsStatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsStatRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsStatRepositoryMockRecorder is the mock recorder for MockJobsStatRepository.
type MockJobsStatRepositoryMockRecorder struct {
	mock *MockJobsStatRepository
}

// NewMockJobsStatRepository creates a new mock instance.
func NewMockJobsStatRepository(ctrl *gomock.Controller) *MockJobsStatRepository {
	mock := &MockJobsStatRepository{ctrl: ctrl}
	mock.recorder = &MockJobsStatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsStatRepository) EXPECT() *MockJobsStatRepositoryMockRecorder {
	return m.recorder
}

// CountAvailable mocks base method.
func (m *MockJobsStatRepository) CountAvailable(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAvailable", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAvailable indicates an expected call of CountAvailable.
func (mr *MockJobsStatRepositoryMockRecorder) CountAvailable(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAvailable", reflect.TypeOf((*MockJobsStatRepository)(nil).CountAvailable), ctx, now)
}

// CountExact mocks base method.
func (m *MockJobsStatRepository) CountExact(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExact", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExact indicates an expected call of CountExact.
func (mr *MockJobsStatRepositoryMockRecorder) CountExact(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExact", reflect.TypeOf((*MockJobsStatRepository)(nil).CountExact), ctx)
}

// CountReserved mocks base method.
func (m *MockJobsStatRepository) CountReserved(ctx context.Context, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountReserved", ctx, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountReserved indicates an expected call of CountReserved.
func (mr *MockJobsStatRepositoryMockRecorder) CountReserved(ctx, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountReserved", reflect.TypeOf((*MockJobsStatRepository)(nil).CountReserved), ctx, now)
}

// MockJobsFailedRepository is a mock of JobsFailedRepository interface.
type MockJobsFailedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsFailedRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsFailedRepositoryMockRecorder is the mock recorder for MockJobsFailedRepository.
type MockJobsFailedRepositoryMockRecorder struct {
	mock *MockJobsFailedRepository
}

// NewMockJobsFailedRepository creates a new mock instance.
func NewMockJobsFailedRepository(ctrl *gomock.Controller) *MockJobsFailedRepository {
	mock := &MockJobsFailedRepository{ctrl: ctrl}
	mock.recorder = &MockJobsFailedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsFailedRepository) EXPECT() *MockJobsFailedRepositoryMockRecorder {
	return m.recorder
}

// CreateFailedJob mocks base method.
func (m *MockJobsFailedRepository) CreateFailedJob(ctx context.Context, jobID types.JobID, name, payload, reason string) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFailedJob", ctx, jobID, name, payload, reason)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFailedJob indicates an expected call of CreateFailedJob.
func (mr *MockJobsFailedRepositoryMockRecorder) CreateFailedJob(ctx, jobID, name, payload, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFailedJob", reflect.TypeOf((*MockJobsFailedRepository)(nil).CreateFailedJob), ctx, jobID, name, payload, reason)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTransactorMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTransactor)(nil).RunInTx), ctx, f)
}

// MockJob is a mock of Job interface.
type MockJob struct {
	ctrl     *gomock.Controller
	recorder *MockJobMockRecorder
	isgomock struct{}
}

// MockJobMockRecorder is the mock recorder for MockJob.
type MockJobMockRecorder struct {
	mock *MockJob
}

// NewMockJob creates a new mock instance.
func NewMockJob(ctrl *gomock.Controller) *MockJob {
	mock := &MockJob{ctrl: ctrl}
	mock.recorder = &MockJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJob) EXPECT() *MockJobMockRecorder {
	return m.recorder
}

// ExecutionTimeout mocks base method.
func (m *MockJob) ExecutionTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ExecutionTimeout indicates an expected call of ExecutionTimeout.
func (mr *MockJobMockRecorder) ExecutionTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionTimeout", reflect.TypeOf((*MockJob)(nil).ExecutionTimeout))
}

// Handle mocks base method.
func (m *MockJob) Handle(ctx context.Context, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockJobMockRecorder) Handle(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockJob)(nil).Handle), ctx, payload)
}

// MaxAttempts mocks base method.
func (m *MockJob) MaxAttempts() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxAttempts")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxAttempts indicates an expected call of MaxAttempts.
func (mr *MockJobMockRecorder) MaxAttempts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxAttempts", reflect.TypeOf((*MockJob)(nil).MaxAttempts))
}

// Name mocks base method.
func (m *MockJob) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockJobMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockJob)(nil).Name))
}
