// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mocks/contract_mock.gen.go -package=outboxmocks
//

// Package outboxmocks is a generated GoMock package.
package outboxmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"

	outbox "github.com/assurrussa/outbox/outbox"
	models "github.com/assurrussa/outbox/outbox/models"
	types "github.com/assurrussa/outbox/shared/types"
)

// MockPutter is a mock of Putter interface.
type MockPutter struct {
	ctrl     *gomock.Controller
	recorder *MockPutterMockRecorder
	isgomock struct{}
}

// MockPutterMockRecorder is the mock recorder for MockPutter.
type MockPutterMockRecorder struct {
	mock *MockPutter
}

// NewMockPutter creates a new mock instance.
func NewMockPutter(ctrl *gomock.Controller) *MockPutter {
	mock := &MockPutter{ctrl: ctrl}
	mock.recorder = &MockPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPutter) EXPECT() *MockPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockVersionedPutter is a mock of VersionedPutter interface.
type MockVersionedPutter struct {
	ctrl     *gomock.Controller
	recorder *MockVersionedPutterMockRecorder
	isgomock struct{}
}

// MockVersionedPutterMockRecorder is the mock recorder for MockVersionedPutter.
type MockVersionedPutterMockRecorder struct {
	mock *MockVersionedPutter
}

// NewMockVersionedPutter creates a new mock instance.
func NewMockVersionedPutter(ctrl *gomock.Controller) *MockVersionedPutter {
	mock := &MockVersionedPutter{ctrl: ctrl}
	mock.recorder = &MockVersionedPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionedPutter) EXPECT() *MockVersionedPutterMockRecorder {
	return m.recorder
}

// PutVersioned mocks base method.
func (m *MockVersionedPutter) PutVersioned(ctx context.Context, name string, schemaVersion outbox.SchemaVersion, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVersioned", ctx, name, schemaVersion, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutVersioned indicates an expected call of PutVersioned.
func (mr *MockVersionedPutterMockRecorder) PutVersioned(ctx, name, schemaVersion, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVersioned", reflect.TypeOf((*MockVersionedPutter)(nil).PutVersioned), ctx, name, schemaVersion, payload, availableAt)
}

// MockUniqueVersionedPutter is a mock of UniqueVersionedPutter interface.
type MockUniqueVersionedPutter struct {
	ctrl     *gomock.Controller
	recorder *MockUniqueVersionedPutterMockRecorder
	isgomock struct{}
}

// MockUniqueVersionedPutterMockRecorder is the mock recorder for MockUniqueVersionedPutter.
type MockUniqueVersionedPutterMockRecorder struct {
	mock *MockUniqueVersionedPutter
}

// NewMockUniqueVersionedPutter creates a new mock instance.
func NewMockUniqueVersionedPutter(ctrl *gomock.Controller) *MockUniqueVersionedPutter {
	mock := &MockUniqueVersionedPutter{ctrl: ctrl}
	mock.recorder = &MockUniqueVersionedPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniqueVersionedPutter) EXPECT() *MockUniqueVersionedPutterMockRecorder {
	return m.recorder
}

// PutVersionedUnique mocks base method.
func (m *MockUniqueVersionedPutter) PutVersionedUnique(ctx context.Context, deduplicationKey, name string, schemaVersion outbox.SchemaVersion, payload string, availableAt time.Time) (outbox.UniquePutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutVersionedUnique", ctx, deduplicationKey, name, schemaVersion, payload, availableAt)
	ret0, _ := ret[0].(outbox.UniquePutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutVersionedUnique indicates an expected call of PutVersionedUnique.
func (mr *MockUniqueVersionedPutterMockRecorder) PutVersionedUnique(ctx, deduplicationKey, name, schemaVersion, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutVersionedUnique", reflect.TypeOf((*MockUniqueVersionedPutter)(nil).PutVersionedUnique), ctx, deduplicationKey, name, schemaVersion, payload, availableAt)
}

// MockFanoutPutter is a mock of FanoutPutter interface.
type MockFanoutPutter struct {
	ctrl     *gomock.Controller
	recorder *MockFanoutPutterMockRecorder
	isgomock struct{}
}

// MockFanoutPutterMockRecorder is the mock recorder for MockFanoutPutter.
type MockFanoutPutterMockRecorder struct {
	mock *MockFanoutPutter
}

// NewMockFanoutPutter creates a new mock instance.
func NewMockFanoutPutter(ctrl *gomock.Controller) *MockFanoutPutter {
	mock := &MockFanoutPutter{ctrl: ctrl}
	mock.recorder = &MockFanoutPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFanoutPutter) EXPECT() *MockFanoutPutterMockRecorder {
	return m.recorder
}

// PutFanout mocks base method.
func (m *MockFanoutPutter) PutFanout(ctx context.Context, event outbox.FanoutEvent, targets []outbox.FanoutTarget, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutFanout", ctx, event, targets, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutFanout indicates an expected call of PutFanout.
func (mr *MockFanoutPutterMockRecorder) PutFanout(ctx, event, targets, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutFanout", reflect.TypeOf((*MockFanoutPutter)(nil).PutFanout), ctx, event, targets, availableAt)
}

// MockStats is a mock of Stats interface.
type MockStats struct {
	ctrl     *gomock.Controller
	recorder *MockStatsMockRecorder
	isgomock struct{}
}

// MockStatsMockRecorder is the mock recorder for MockStats.
type MockStatsMockRecorder struct {
	mock *MockStats
}

// NewMockStats creates a new mock instance.
func NewMockStats(ctrl *gomock.Controller) *MockStats {
	mock := &MockStats{ctrl: ctrl}
	mock.recorder = &MockStatsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStats) EXPECT() *MockStatsMockRecorder {
	return m.recorder
}

// QueueStats mocks base method.
func (m *MockStats) QueueStats(ctx context.Context) (outbox.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueueStats", ctx)
	ret0, _ := ret[0].(outbox.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueStats indicates an expected call of QueueStats.
func (mr *MockStatsMockRecorder) QueueStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueStats", reflect.TypeOf((*MockStats)(nil).QueueStats), ctx)
}

// MockJobsRepository is a mock of JobsRepository interface.
type MockJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsRepositoryMockRecorder is the mock recorder for MockJobsRepository.
type MockJobsRepositoryMockRecorder struct {
	mock *MockJobsRepository
}

// NewMockJobsRepository creates a new mock instance.
func NewMockJobsRepository(ctrl *gomock.Controller) *MockJobsRepository {
	mock := &MockJobsRepository{ctrl: ctrl}
	mock.recorder = &MockJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsRepository) EXPECT() *MockJobsRepositoryMockRecorder {
	return m.recorder
}

// CreateJobVersioned mocks base method.
func (m *MockJobsRepository) CreateJobVersioned(ctx context.Context, name string, schemaVersion outbox.SchemaVersion, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJobVersioned", ctx, name, schemaVersion, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJobVersioned indicates an expected call of CreateJobVersioned.
func (mr *MockJobsRepositoryMockRecorder) CreateJobVersioned(ctx, name, schemaVersion, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJobVersioned", reflect.TypeOf((*MockJobsRepository)(nil).CreateJobVersioned), ctx, name, schemaVersion, payload, availableAt)
}

// DeleteJobWithLease mocks base method.
func (m *MockJobsRepository) DeleteJobWithLease(ctx context.Context, jobID types.JobID, leaseToken outbox.LeaseToken, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJobWithLease", ctx, jobID, leaseToken, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJobWithLease indicates an expected call of DeleteJobWithLease.
func (mr *MockJobsRepositoryMockRecorder) DeleteJobWithLease(ctx, jobID, leaseToken, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJobWithLease", reflect.TypeOf((*MockJobsRepository)(nil).DeleteJobWithLease), ctx, jobID, leaseToken, now)
}

// ExtendJobLeases mocks base method.
func (m *MockJobsRepository) ExtendJobLeases(ctx context.Context, jobIDs []types.JobID, leaseToken outbox.LeaseToken, now, until time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtendJobLeases", ctx, jobIDs, leaseToken, now, until)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtendJobLeases indicates an expected call of ExtendJobLeases.
func (mr *MockJobsRepositoryMockRecorder) ExtendJobLeases(ctx, jobIDs, leaseToken, now, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtendJobLeases", reflect.TypeOf((*MockJobsRepository)(nil).ExtendJobLeases), ctx, jobIDs, leaseToken, now, until)
}

// FindAndReserveJobsForCapabilities mocks base method.
func (m *MockJobsRepository) FindAndReserveJobsForCapabilities(ctx context.Context, now, until time.Time, leaseToken outbox.LeaseToken, capabilities []outbox.JobCapability, limit int) ([]models.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAndReserveJobsForCapabilities", ctx, now, until, leaseToken, capabilities, limit)
	ret0, _ := ret[0].([]models.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAndReserveJobsForCapabilities indicates an expected call of FindAndReserveJobsForCapabilities.
func (mr *MockJobsRepositoryMockRecorder) FindAndReserveJobsForCapabilities(ctx, now, until, leaseToken, capabilities, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAndReserveJobsForCapabilities", reflect.TypeOf((*MockJobsRepository)(nil).FindAndReserveJobsForCapabilities), ctx, now, until, leaseToken, capabilities, limit)
}

// MaxReservationBatchSize mocks base method.
func (m *MockJobsRepository) MaxReservationBatchSize() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxReservationBatchSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxReservationBatchSize indicates an expected call of MaxReservationBatchSize.
func (mr *MockJobsRepositoryMockRecorder) MaxReservationBatchSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxReservationBatchSize", reflect.TypeOf((*MockJobsRepository)(nil).MaxReservationBatchSize))
}

// ReleaseUnstartedJobsWithLease mocks base method.
func (m *MockJobsRepository) ReleaseUnstartedJobsWithLease(ctx context.Context, jobIDs []types.JobID, leaseToken outbox.LeaseToken, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseUnstartedJobsWithLease", ctx, jobIDs, leaseToken, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseUnstartedJobsWithLease indicates an expected call of ReleaseUnstartedJobsWithLease.
func (mr *MockJobsRepositoryMockRecorder) ReleaseUnstartedJobsWithLease(ctx, jobIDs, leaseToken, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseUnstartedJobsWithLease", reflect.TypeOf((*MockJobsRepository)(nil).ReleaseUnstartedJobsWithLease), ctx, jobIDs, leaseToken, now)
}

// RescheduleJobWithLease mocks base method.
func (m *MockJobsRepository) RescheduleJobWithLease(ctx context.Context, jobID types.JobID, leaseToken outbox.LeaseToken, now, availableAt time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RescheduleJobWithLease", ctx, jobID, leaseToken, now, availableAt)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RescheduleJobWithLease indicates an expected call of RescheduleJobWithLease.
func (mr *MockJobsRepositoryMockRecorder) RescheduleJobWithLease(ctx, jobID, leaseToken, now, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RescheduleJobWithLease", reflect.TypeOf((*MockJobsRepository)(nil).RescheduleJobWithLease), ctx, jobID, leaseToken, now, availableAt)
}

// MockFanoutJobsRepository is a mock of FanoutJobsRepository interface.
type MockFanoutJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFanoutJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockFanoutJobsRepositoryMockRecorder is the mock recorder for MockFanoutJobsRepository.
type MockFanoutJobsRepositoryMockRecorder struct {
	mock *MockFanoutJobsRepository
}

// NewMockFanoutJobsRepository creates a new mock instance.
func NewMockFanoutJobsRepository(ctrl *gomock.Controller) *MockFanoutJobsRepository {
	mock := &MockFanoutJobsRepository{ctrl: ctrl}
	mock.recorder = &MockFanoutJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFanoutJobsRepository) EXPECT() *MockFanoutJobsRepositoryMockRecorder {
	return m.recorder
}

// CreateJobVersionedUnique mocks base method.
func (m *MockFanoutJobsRepository) CreateJobVersionedUnique(ctx context.Context, deduplicationKey, name string, schemaVersion outbox.SchemaVersion, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJobVersionedUnique", ctx, deduplicationKey, name, schemaVersion, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJobVersionedUnique indicates an expected call of CreateJobVersionedUnique.
func (mr *MockFanoutJobsRepositoryMockRecorder) CreateJobVersionedUnique(ctx, deduplicationKey, name, schemaVersion, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJobVersionedUnique", reflect.TypeOf((*MockFanoutJobsRepository)(nil).CreateJobVersionedUnique), ctx, deduplicationKey, name, schemaVersion, payload, availableAt)
}

// MockUniqueJobsRepository is a mock of UniqueJobsRepository interface.
type MockUniqueJobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUniqueJobsRepositoryMockRecorder
	isgomock struct{}
}

// MockUniqueJobsRepositoryMockRecorder is the mock recorder for MockUniqueJobsRepository.
type MockUniqueJobsRepositoryMockRecorder struct {
	mock *MockUniqueJobsRepository
}

// NewMockUniqueJobsRepository creates a new mock instance.
func NewMockUniqueJobsRepository(ctrl *gomock.Controller) *MockUniqueJobsRepository {
	mock := &MockUniqueJobsRepository{ctrl: ctrl}
	mock.recorder = &MockUniqueJobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUniqueJobsRepository) EXPECT() *MockUniqueJobsRepositoryMockRecorder {
	return m.recorder
}

// CreateJobVersionedUniqueResult mocks base method.
func (m *MockUniqueJobsRepository) CreateJobVersionedUniqueResult(ctx context.Context, deduplicationKey, name string, schemaVersion outbox.SchemaVersion, payload string, availableAt time.Time) (outbox.UniquePutResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJobVersionedUniqueResult", ctx, deduplicationKey, name, schemaVersion, payload, availableAt)
	ret0, _ := ret[0].(outbox.UniquePutResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJobVersionedUniqueResult indicates an expected call of CreateJobVersionedUniqueResult.
func (mr *MockUniqueJobsRepositoryMockRecorder) CreateJobVersionedUniqueResult(ctx, deduplicationKey, name, schemaVersion, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJobVersionedUniqueResult", reflect.TypeOf((*MockUniqueJobsRepository)(nil).CreateJobVersionedUniqueResult), ctx, deduplicationKey, name, schemaVersion, payload, availableAt)
}

// MockFanoutMaintenanceRepository is a mock of FanoutMaintenanceRepository interface.
type MockFanoutMaintenanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFanoutMaintenanceRepositoryMockRecorder
	isgomock struct{}
}

// MockFanoutMaintenanceRepositoryMockRecorder is the mock recorder for MockFanoutMaintenanceRepository.
type MockFanoutMaintenanceRepositoryMockRecorder struct {
	mock *MockFanoutMaintenanceRepository
}

// NewMockFanoutMaintenanceRepository creates a new mock instance.
func NewMockFanoutMaintenanceRepository(ctrl *gomock.Controller) *MockFanoutMaintenanceRepository {
	mock := &MockFanoutMaintenanceRepository{ctrl: ctrl}
	mock.recorder = &MockFanoutMaintenanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFanoutMaintenanceRepository) EXPECT() *MockFanoutMaintenanceRepositoryMockRecorder {
	return m.recorder
}

// PruneJobIdempotencyKeys mocks base method.
func (m *MockFanoutMaintenanceRepository) PruneJobIdempotencyKeys(ctx context.Context, before time.Time, limit int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneJobIdempotencyKeys", ctx, before, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PruneJobIdempotencyKeys indicates an expected call of PruneJobIdempotencyKeys.
func (mr *MockFanoutMaintenanceRepositoryMockRecorder) PruneJobIdempotencyKeys(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneJobIdempotencyKeys", reflect.TypeOf((*MockFanoutMaintenanceRepository)(nil).PruneJobIdempotencyKeys), ctx, before, limit)
}

// MockJobsStatRepository is a mock of JobsStatRepository interface.
type MockJobsStatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsStatRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsStatRepositoryMockRecorder is the mock recorder for MockJobsStatRepository.
type MockJobsStatRepositoryMockRecorder struct {
	mock *MockJobsStatRepository
}

// NewMockJobsStatRepository creates a new mock instance.
func NewMockJobsStatRepository(ctrl *gomock.Controller) *MockJobsStatRepository {
	mock := &MockJobsStatRepository{ctrl: ctrl}
	mock.recorder = &MockJobsStatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsStatRepository) EXPECT() *MockJobsStatRepositoryMockRecorder {
	return m.recorder
}

// GetQueueStats mocks base method.
func (m *MockJobsStatRepository) GetQueueStats(ctx context.Context, observedAt time.Time) (outbox.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueStats", ctx, observedAt)
	ret0, _ := ret[0].(outbox.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueStats indicates an expected call of GetQueueStats.
func (mr *MockJobsStatRepositoryMockRecorder) GetQueueStats(ctx, observedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueStats", reflect.TypeOf((*MockJobsStatRepository)(nil).GetQueueStats), ctx, observedAt)
}

// MockJobsFailedRepository is a mock of JobsFailedRepository interface.
type MockJobsFailedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobsFailedRepositoryMockRecorder
	isgomock struct{}
}

// MockJobsFailedRepositoryMockRecorder is the mock recorder for MockJobsFailedRepository.
type MockJobsFailedRepositoryMockRecorder struct {
	mock *MockJobsFailedRepository
}

// NewMockJobsFailedRepository creates a new mock instance.
func NewMockJobsFailedRepository(ctrl *gomock.Controller) *MockJobsFailedRepository {
	mock := &MockJobsFailedRepository{ctrl: ctrl}
	mock.recorder = &MockJobsFailedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobsFailedRepository) EXPECT() *MockJobsFailedRepositoryMockRecorder {
	return m.recorder
}

// CreateFailedJobVersioned mocks base method.
func (m *MockJobsFailedRepository) CreateFailedJobVersioned(ctx context.Context, jobID types.JobID, name string, schemaVersion outbox.SchemaVersion, payload, reason string) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFailedJobVersioned", ctx, jobID, name, schemaVersion, payload, reason)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFailedJobVersioned indicates an expected call of CreateFailedJobVersioned.
func (mr *MockJobsFailedRepositoryMockRecorder) CreateFailedJobVersioned(ctx, jobID, name, schemaVersion, payload, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFailedJobVersioned", reflect.TypeOf((*MockJobsFailedRepository)(nil).CreateFailedJobVersioned), ctx, jobID, name, schemaVersion, payload, reason)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
	isgomock struct{}
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTransactorMockRecorder) RunInTx(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTransactor)(nil).RunInTx), ctx, f)
}

// MockTransactionCapabilities is a mock of TransactionCapabilities interface.
type MockTransactionCapabilities struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionCapabilitiesMockRecorder
	isgomock struct{}
}

// MockTransactionCapabilitiesMockRecorder is the mock recorder for MockTransactionCapabilities.
type MockTransactionCapabilitiesMockRecorder struct {
	mock *MockTransactionCapabilities
}

// NewMockTransactionCapabilities creates a new mock instance.
func NewMockTransactionCapabilities(ctrl *gomock.Controller) *MockTransactionCapabilities {
	mock := &MockTransactionCapabilities{ctrl: ctrl}
	mock.recorder = &MockTransactionCapabilitiesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionCapabilities) EXPECT() *MockTransactionCapabilitiesMockRecorder {
	return m.recorder
}

// SupportsAtomicDLQ mocks base method.
func (m *MockTransactionCapabilities) SupportsAtomicDLQ() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportsAtomicDLQ")
	ret0, _ := ret[0].(bool)
	return ret0
}

// SupportsAtomicDLQ indicates an expected call of SupportsAtomicDLQ.
func (mr *MockTransactionCapabilitiesMockRecorder) SupportsAtomicDLQ() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportsAtomicDLQ", reflect.TypeOf((*MockTransactionCapabilities)(nil).SupportsAtomicDLQ))
}

// MockJob is a mock of Job interface.
type MockJob struct {
	ctrl     *gomock.Controller
	recorder *MockJobMockRecorder
	isgomock struct{}
}

// MockJobMockRecorder is the mock recorder for MockJob.
type MockJobMockRecorder struct {
	mock *MockJob
}

// NewMockJob creates a new mock instance.
func NewMockJob(ctrl *gomock.Controller) *MockJob {
	mock := &MockJob{ctrl: ctrl}
	mock.recorder = &MockJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJob) EXPECT() *MockJobMockRecorder {
	return m.recorder
}

// ExecutionTimeout mocks base method.
func (m *MockJob) ExecutionTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// ExecutionTimeout indicates an expected call of ExecutionTimeout.
func (mr *MockJobMockRecorder) ExecutionTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionTimeout", reflect.TypeOf((*MockJob)(nil).ExecutionTimeout))
}

// Handle mocks base method.
func (m *MockJob) Handle(ctx context.Context, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockJobMockRecorder) Handle(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockJob)(nil).Handle), ctx, payload)
}

// MaxAttempts mocks base method.
func (m *MockJob) MaxAttempts() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxAttempts")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxAttempts indicates an expected call of MaxAttempts.
func (mr *MockJobMockRecorder) MaxAttempts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxAttempts", reflect.TypeOf((*MockJob)(nil).MaxAttempts))
}

// Name mocks base method.
func (m *MockJob) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockJobMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockJob)(nil).Name))
}
